import { useState } from 'react';
import { useFetch } from '../../hooks/useFetch';
import { selfServiceApi } from '../../api/selfService';
import { payslipApi } from '../../api/payslips';
import Card from '../../components/ui/Card';
import Loading from '../../components/ui/Loading';
import ErrorState from '../../components/ui/ErrorState';
import EmptyState from '../../components/ui/EmptyState';
import StatusBadge from '../../components/ui/StatusBadge';
import Button from '../../components/ui/Button';
import Modal from '../../components/ui/Modal';
import { useToast } from '../../context/ToastContext';
import { FileText, Download, Eye, DollarSign } from 'lucide-react';

export default function MyPayslips() {
  const { success, error } = useToast();
  const { data: payslips, loading, error: fetchError, refetch } = useFetch(selfServiceApi.getPayslips);
  const [selectedPayslip, setSelectedPayslip] = useState(null);
  const [downloadingId, setDownloadingId] = useState(null);

  const handleDownload = async (id, filename) => {
    setDownloadingId(id);
    try {
      const response = await payslipApi.downloadPdf(id);
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const link = document.createElement('a');
      link.href = window.URL.createObjectURL(blob);
      link.download = filename || `payslip-${id}.pdf`;
      link.click();
      success('Payslip downloaded successfully!');
    } catch (err) {
      console.error(err);
      error('Failed to download payslip PDF.');
    } finally {
      setDownloadingId(null);
    }
  };

  if (loading) return <Loading />;
  if (fetchError) return <ErrorState message={fetchError} onRetry={refetch} />;

  const list = payslips || [];

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">My Payslips</h1>
          <p className="page-subtitle">View and download your monthly salary statements</p>
        </div>
      </div>

      {list.length === 0 ? (
        <Card className="card-padded">
          <EmptyState 
            title="No payslips generated" 
            description="Your payslips will appear here once generated by HR/Admin." 
          />
        </Card>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '24px' }} className="lg:grid-cols-3">
          {/* List Card */}
          <div style={{ gridColumn: 'span 2' }}>
            <Card>
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Pay Period</th>
                    <th>Net Salary</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {list.map(p => (
                    <tr key={p._id} style={{ cursor: 'pointer' }} onClick={() => setSelectedPayslip(p)}>
                      <td style={{ fontWeight: 600 }}>{p.month}/{p.year}</td>
                      <td>₹{p.netSalary?.toLocaleString()}</td>
                      <td>
                        <StatusBadge status={p.status || 'PAID'} />
                      </td>
                      <td>
                        <div style={{ display: 'flex', gap: '8px' }} onClick={e => e.stopPropagation()}>
                          <button onClick={() => setSelectedPayslip(p)} className="btn btn-secondary btn-sm" style={{ padding: '6px' }}>
                            <Eye size={14} />
                          </button>
                          <button 
                            onClick={() => handleDownload(p._id, `payslip-${p.month}-${p.year}.pdf`)} 
                            className="btn btn-secondary btn-sm" 
                            style={{ padding: '6px' }}
                            disabled={downloadingId === p._id}
                          >
                            <Download size={14} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </Card>
          </div>

          {/* Details Column / Card */}
          <div>
            {selectedPayslip ? (
              <Card className="card-padded-lg" style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                <h3 style={{ fontSize: '15px', fontWeight: 600, margin: 0, borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>
                  Payslip Details ({selectedPayslip.month}/{selectedPayslip.year})
                </h3>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '13.5px' }}>
                  <div className="detail-field">
                    <span className="detail-label">Status</span>
                    <span className="detail-value"><StatusBadge status={selectedPayslip.status || 'PAID'} /></span>
                  </div>
                  <div className="detail-field">
                    <span className="detail-label">Basic Salary</span>
                    <span className="detail-value">₹{selectedPayslip.basicSalary?.toLocaleString()}</span>
                  </div>
                  <div className="detail-field">
                    <span className="detail-label">Allowances</span>
                    <span className="detail-value" style={{ color: 'var(--success)' }}>+₹{selectedPayslip.allowances?.toLocaleString()}</span>
                  </div>
                  <div className="detail-field">
                    <span className="detail-label">Deductions</span>
                    <span className="detail-value" style={{ color: 'var(--danger)' }}>-₹{selectedPayslip.deductions?.toLocaleString()}</span>
                  </div>
                  <div className="detail-field" style={{ borderTop: '1px solid var(--border-subtle)', paddingTop: '10px', fontWeight: 700 }}>
                    <span className="detail-label">Net Salary</span>
                    <span className="detail-value">₹{selectedPayslip.netSalary?.toLocaleString()}</span>
                  </div>
                </div>

                <Button 
                  onClick={() => handleDownload(selectedPayslip._id, `payslip-${selectedPayslip.month}-${selectedPayslip.year}.pdf`)}
                  style={{ width: '100%', gap: '8px' }}
                  disabled={downloadingId === selectedPayslip._id}
                >
                  <Download size={15} /> Download PDF Payslip
                </Button>
              </Card>
            ) : (
              <Card className="card-padded" style={{ textAlign: 'center', color: 'var(--text-secondary)' }}>
                <DollarSign size={24} style={{ margin: '0 auto 8px', color: 'var(--text-muted)' }} />
                <p style={{ fontSize: '13px', margin: 0 }}>Select a payslip to view details breakdown.</p>
              </Card>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
